<?xml version="1.0" encoding="utf-8"?><Database Name="Api" Class="SessionsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=www.scholarbarter.com;Initial Catalog=Api;Persist Security Info=True;User ID=scholaruser" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ApiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Sessions" Member="Sessions">
    <Type Name="Session">
      <Column Name="SessionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SessionKey" Type="System.String" DbType="Char(32) NOT NULL" CanBeNull="false" />
      <Column Name="ValidationTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>